services:
  - type: web
    name: daily-report-rogerio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
# force redeploy Fri Jun 12 16:54:24 UTC 2026 ts=1781283264
